apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api-deployment
  labels:
    app: fraud-api
spec:
  replicas: 4  # Для начала 4
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      containers:
      - name: fraud-api-container
        image: {{IMAGE_PLACEHOLDER}} 
        imagePullPolicy: IfNotPresent # для локальной разработки
        ports:
        - containerPort: 8000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "{{MLFLOW_URL}}"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{KAFKA_URL}}"
        - name: KAFKA_USER
          value: "{{KAFKA_USER}}"
        - name: KAFKA_PASS
          value: "{{KAFKA_PASS}}"
        - name: KAFKA_TOPIC_OUT
          value: "predictions"
        resources:
          requests:
            cpu: "200m"    
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        # Проверки работоспособности
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5