apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-to-api-forwarder
  labels:
    app: kafka-to-api-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-to-api-forwarder
  template:
    metadata:
      labels:
        app: kafka-to-api-forwarder
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
         nameservers:
          - 169.254.169.254
      containers:
      - name: forwarder-container
        image: cr.yandex/crp7l4h5pj2mreg8j5a9/fraud-api-forwarder:8510f40002c06e4e2a27281c0b408082735449cf
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "rc1a-onmdhh3gada2v6sa.mdb.yandexcloud.net:9091"
        - name: KAFKA_USER
          value: "ml_user"
        - name: KAFKA_PASS
          value: "@StarGate-123k"
        - name: KAFKA_TOPIC_IN
          value: "for_ml_fraud" # Топик, куда пишет Spark
        #  API через имя сервиса
        - name: FRAUD_API_URL
          value: "http://fraud-app:80/predict" 
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
