apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-to-api-forwarder
  labels:
    app: kafka-to-api-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-to-api-forwarder
  template:
    metadata:
      labels:
        app: kafka-to-api-forwarder
    spec:
      # dnsPolicy: ClusterFirst
      # dnsConfig:
      #   nameservers:
      #     - 169.254.169.254
      containers:
      - name: forwarder-container
        image: cr.yandex/crpd33maugkidd7j102q/fraud-api-forwarder:724695544aa44053b5f2584263301c94e5671f94
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "rc1a-0s2cfdsfkkv50slk.mdb.yandexcloud.net:9091"
        - name: KAFKA_USER
          value: "ml_user"
        - name: KAFKA_PASS
          value: "@StarGate-123k"
        - name: KAFKA_TOPIC_IN
          value: "for_ml_fraud" # Топик, куда пишет Spark
        #  API через имя сервиса
        - name: FRAUD_API_URL
          value: "http://fraud-app:80/predict" 
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
