apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-proc-job
  namespace: spark
spec:
  type: Python
  mode: cluster
  image: cr.yandex/crpd33maugkidd7j102q/clean-data:96685f75d7104fd8cdda256022a859913842037d
  mainApplicationFile: local:///app/clean_and_prepare.py
  sparkVersion: "3.3.2"

  driver:
    cores: 2
    memory: "2g"
    serviceAccount: spark
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "rc1a-0s2cfdsfkkv50slk.mdb.yandexcloud.net:9091"
      - name: KAFKA_USER
        value: "ml_user"
      - name: KAFKA_PASS
        value: "@StarGate-123k"
      - name: KAFKA_TOPIC_IN
        value: "raw_data"
      - name: KAFKA_TOPIC_OUT
        value: "for_ml_fraud"

  executor:
    cores: 2
    memory: "3g"
    # Дублируем переменные для исполнителей, если они нужны в коде трансформаций
    env:
      - name: KAFKA_BOOTSTRAP_SERVERS
        value: "rc1a-0s2cfdsfkkv50slk.mdb.yandexcloud.net:9091"

  sparkConf:
    "spark.dynamicAllocation.enabled": "true"
    "spark.dynamicAllocation.minExecutors": "1"
    "spark.dynamicAllocation.maxExecutors": "5"
    "spark.dynamicAllocation.initialExecutors": "2"
    "spark.dynamicAllocation.shuffleTracking.enabled": "true"
    
    # S3 / Object Storage
    "spark.sql.streaming.checkpointLocation": "s3a://otus-bucket3-b1gukkncvsp3tvci7gp3/checkpoints"
    "spark.hadoop.fs.s3a.endpoint": "storage.yandexcloud.net"
    "spark.hadoop.fs.s3a.access.key": "YCAJEuZoqlL75ITFTbZWi-rhF"
    "spark.hadoop.fs.s3a.secret.key": "YCMwLEOL5ZuayYKCYAWnOfdWBvOOM__5Eea8Bjo0"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.path.style.access": "true"
    "spark.hadoop.fs.s3a.endpoint.region":  "ru-central1"
    "com.amazonaws.services.s3.enableV4": "true"
    "spark.hadoop.fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"

    # Kafka Security (SASL_SSL)
    "spark.kafka.bootstrap.servers": "rc1a-0s2cfdsfkkv50slk.mdb.yandexcloud.net:9091"
    "spark.kafka.subscribe": "your_input_topic"
    "spark.kafka.kafka.security.protocol": "SASL_SSL"
    "spark.kafka.kafka.sasl.mechanism": "SCRAM-SHA-512"
    "spark.kafka.kafka.sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username='ml_user' password='@StarGate-123k';"
    
    "spark.kubernetes.executorEnv.KAFKA_BOOTSTRAP_SERVERS": "rc1a-0s2cfdsfkkv50slk.mdb.yandexcloud.net:9091"
    "spark.kubernetes.executorEnv.KAFKA_USER": "ml_user"
    "spark.kubernetes.executorEnv.KAFKA_PASS": "@StarGate-123k"
    "spark.kubernetes.executorEnv.KAFKA_TOPIC_IN": "raw_data"
    "spark.kubernetes.executorEnv.KAFKA_TOPIC_OUT": "for_ml_fraud"
    "spark.kubernetes.executorEnv.PERSIST_BUCKET_NAME": "otus-bucket3-b1gukkncvsp3tvci7gp3"

    "spark.kubernetes.driverEnv.KAFKA_BOOTSTRAP_SERVERS": "rc1a-0s2cfdsfkkv50slk.mdb.yandexcloud.net:9091"
    "spark.kubernetes.driverEnv.KAFKA_USER": "ml_user"
    "spark.kubernetes.driverEnv.KAFKA_PASS": "@StarGate-123k"
    "spark.kubernetes.driverEnv.KAFKA_TOPIC_IN": "raw_data"
    "spark.kubernetes.driverEnv.KAFKA_TOPIC_OUT": "for_ml_fraud"
    "spark.kubernetes.driverEnv.PERSIST_BUCKET_NAME": "otus-bucket3-b1gukkncvsp3tvci7gp3"

    #"spark.jars.packages" : "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.2,org.apache.hadoop:hadoop-aws:3.3.2,com.amazonaws:aws-java-sdk-bundle:1.11.1026"
    # Если не хотите возиться с сертификатом внутри Docker:
    #"spark.kafka.kafka.ssl.endpoint.identification.algorithm": ""