name: CI/CD

on:
  push:
    branches:
      - main

env:
  YC_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
  YC_S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  YC_S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  YC_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT_URL }}
  YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      dags: ${{ steps.filter.outputs.dags }}
      src: ${{ steps.filter.outputs.src }}
      spark: ${{ steps.filter.outputs.spark }}
      forwarder: ${{ steps.filter.outputs.forwarder }}
      model: ${{ steps.filter.outputs.model }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dags: ['dags/**']
            src: ['src/**']
            spark: ['spark-app/**']
            forwarder: ['restapi-forwarder/**']
            model: ['restapi/**']

  # Ваши существующие задачи для Airflow
  sync-dags:
    needs: changes
    if: ${{ needs.changes.outputs.dags == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ env.YC_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ env.YC_S3_ENDPOINT }}
          SOURCE_DIR: 'dags'
          DEST_DIR: 'dags'

  upload-src:
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ env.YC_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ env.YC_S3_ENDPOINT }}
          SOURCE_DIR: 'src'
          DEST_DIR: 'src'
  
  # SPARK CLEAN JOB
  clean-and-prepair-data:
    needs: changes
    if: ${{ needs.changes.outputs.spark == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Deploy
      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -y
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate with Yandex Cloud
        run: |
          # Явно определяем переменную пути для этого шага
          YC_BIN=$HOME/yandex-cloud/bin/yc
          
          echo '${{ secrets.YC_SA_JSON_KEY }}' > sa-key.json
          
          # Используем полный путь к бинарнику
          $YC_BIN config set service-account-key sa-key.json
          $YC_BIN config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          $YC_BIN config set folder-id ${{ secrets.YC_FOLDER_ID }}
          
          # Настройка docker тоже через полный путь
          $YC_BIN container registry configure-docker

      - name: Build and Push Image
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/clean-data:${{ github.sha }}
          yc container registry configure-docker
          docker build -t $IMAGE_PATH -f spark-app/Dockerfile spark-app/
          docker push $IMAGE_PATH

      - name: Prepare and Upload K8s Manifests to S3
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/clean-data:${{ github.sha }}
          KAFKA_URL="${{ secrets.KAFKA_FQDN }}:${{ secrets.KAFKA_PORT }}"

          # Заменяем образ и адрес Kafka в шаблоне
          sed -e "s|{{IMAGE_PLACEHOLDER}}|$IMAGE_PATH|g" \
              -e "s|{{KAFKA_URL}}|$KAFKA_URL|g" \
              -e "s|{{KAFKA_USER}}|${{ secrets.KAFKA_USER }}|g" \
              -e "s|{{KAFKA_PASS}}|${{ secrets.KAFKA_PASS }}|g" \
              -e "s|{{PERSIST_BUCKET_NAME}}|${{ secrets.PERSIST_BUCKET_NAME }}|g" \
              -e "s|{{PERSIST_BUCKET_KEY}}|${{ secrets.PERSIST_BUCKET_KEY }}|g" \
              -e "s|{{PERSIST_BUCKET_SECRET}}|${{ secrets.PERSIST_BUCKET_SECRET }}|g" \
              spark-app/k8s/spark-app-template.yaml > spark-app-template.yaml
          
          # Загружаем готовый файлы в S3
          aws s3 cp spark-app-template.yaml s3://${{ env.YC_S3_BUCKET }}/k8s/spark-app-template.yaml --endpoint-url ${{ env.YC_S3_ENDPOINT }}

        env:
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          
      - name: Get Kubeconfig and Deploy
        run: |
          # 1. Генерируем конфиг (он ложится в ~/.kube/config)
          yc managed-kubernetes cluster get-credentials ${{ secrets.KUBER_ID }} --external
          
          # 2. kubectl сам подхватит его из ~/.kube/config
          kubectl cluster-info  # Проверка связи
          
          # 3. Деплоим
          kubectl apply -f spark-app-template.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
  
  # FORWARDER
  forward_to_predictions:
    needs: changes
    if: ${{ needs.changes.outputs.forwarder == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
     
      # Deploy
      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -y
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate with Yandex Cloud
        run: |
          # Явно определяем переменную пути для этого шага
          YC_BIN=$HOME/yandex-cloud/bin/yc
          
          echo '${{ secrets.YC_SA_JSON_KEY }}' > sa-key.json
          
          # Используем полный путь к бинарнику
          $YC_BIN config set service-account-key sa-key.json
          $YC_BIN config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          $YC_BIN config set folder-id ${{ secrets.YC_FOLDER_ID }}
          
          # Настройка docker тоже через полный путь
          $YC_BIN container registry configure-docker

      - name: Build and Push Image
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/fraud-api-forwarder:${{ github.sha }}
          yc container registry configure-docker
          docker build -t $IMAGE_PATH -f restapi-forwarder/Dockerfile restapi-forwarder/
          docker push $IMAGE_PATH

      - name: Prepare and Upload K8s Manifests to S3
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/fraud-api-forwarder:${{ github.sha }}
          KAFKA_URL="${{ secrets.KAFKA_FQDN }}:${{ secrets.KAFKA_PORT }}"

          KAFKA_HOSTS_JSON=$(yc managed-kafka cluster list-hosts --id ${{ secrets.KAFKA_CLUSTER_ID }} --format json)

          # Важно: используем .[0] для обращения к первому элементу массива
          KAFKA_IP=$(echo $KAFKA_HOSTS_JSON | jq -r '.[0].network_interface.ip_address')
          KAFKA_FQDN=$(echo $KAFKA_HOSTS_JSON | jq -r '.[0].name')

          echo "Detected Kafka IP: $KAFKA_IP for Host: $KAFKA_FQDN"

          # 2. Заменяем заглушки, включая новые для HostAliases
          sed -e "s|{{IMAGE_PLACEHOLDER}}|$IMAGE_PATH|g" \
              -e "s|{{KAFKA_URL}}|$KAFKA_URL|g" \
              -e "s|{{KAFKA_USER}}|${{ secrets.KAFKA_USER }}|g" \
              -e "s|{{KAFKA_PASS}}|${{ secrets.KAFKA_PASS }}|g" \
              -e "s|{{KAFKA_IP}}|$KAFKA_IP|g" \
              -e "s|{{KAFKA_HOST}}|$KAFKA_FQDN|g" \
              restapi-forwarder/k8s/deployment-template.yaml > deployment-forwarder.yaml
          
          # Загружаем готовые файлы в S3
          aws s3 cp deployment-forwarder.yaml s3://${{ env.YC_S3_BUCKET }}/k8s/deployment-forwarder.yaml --endpoint-url ${{ env.YC_S3_ENDPOINT }}

        env:
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          
      - name: Get Kubeconfig and Deploy
        run: |
          # 1. Генерируем конфиг (он ложится в ~/.kube/config)
          yc managed-kubernetes cluster get-credentials ${{ secrets.KUBER_ID }} --external
          
          # 2. kubectl сам подхватит его из ~/.kube/config
          kubectl cluster-info  # Проверка связи
          
          # 3. Деплоим
          kubectl apply -f deployment-forwarder.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}

  # REST API
  build-and-deploy-model:
    needs: changes
    if: ${{ needs.changes.outputs.model == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Тесты  
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run Tests
        run: |
          pip install pytest pandas numpy pydantic loguru mlflow pyspark fastapi mlflow aiokafka
          export PYTHONPATH=$PYTHONPATH:$(pwd)/restapi:$(pwd)/restapi/scripts
          pytest restapi/tests/
      
      # Deploy
      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -y
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate with Yandex Cloud
        run: |
          # Явно определяем переменную пути для этого шага
          YC_BIN=$HOME/yandex-cloud/bin/yc
          
          echo '${{ secrets.YC_SA_JSON_KEY }}' > sa-key.json
          
          # Используем полный путь к бинарнику
          $YC_BIN config set service-account-key sa-key.json
          $YC_BIN config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          $YC_BIN config set folder-id ${{ secrets.YC_FOLDER_ID }}
          
          # Настройка docker тоже через полный путь
          $YC_BIN container registry configure-docker

      - name: Build and Push Image
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/fraud-api:${{ github.sha }}
          yc container registry configure-docker
          docker build -t $IMAGE_PATH -f restapi/Dockerfile restapi/
          docker push $IMAGE_PATH

      - name: Prepare and Upload K8s Manifests to S3
        run: |
          IMAGE_PATH=cr.yandex/${{ env.YC_REGISTRY_ID }}/fraud-api:${{ github.sha }}
          MLFLOW_URL="http://${{ secrets.MLFLOW_IP }}:${{ secrets.MLFLOW_PORT }}"
          KAFKA_URL="${{ secrets.KAFKA_FQDN }}:${{ secrets.KAFKA_PORT }}"

          # Заменяем образ, адрес MLFlow и адрес Kafka в шаблоне
          sed -e "s|{{IMAGE_PLACEHOLDER}}|$IMAGE_PATH|g" \
              -e "s|{{MLFLOW_URL}}|$MLFLOW_URL|g" \
              -e "s|{{KAFKA_URL}}|$KAFKA_URL|g" \
              -e "s|{{KAFKA_USER}}|${{ secrets.KAFKA_USER }}|g" \
              -e "s|{{KAFKA_PASS}}|${{ secrets.KAFKA_PASS }}|g" \
              restapi/k8s/deployment-template.yaml > deployment.yaml
          
          sed -e "s|{{SUBNET_ID}}|${{ secrets.SUBNET_ID }}|g" \
              restapi/k8s/service-template.yaml > service.yaml
          
          # Загружаем готовые файлы в S3
          aws s3 cp deployment.yaml s3://${{ env.YC_S3_BUCKET }}/k8s/deployment.yaml --endpoint-url ${{ env.YC_S3_ENDPOINT }}
          aws s3 cp service.yaml s3://${{ env.YC_S3_BUCKET }}/k8s/service.yaml --endpoint-url ${{ env.YC_S3_ENDPOINT }}
          aws s3 cp restapi/k8s/hpa.yaml s3://${{ env.YC_S3_BUCKET }}/k8s/service.yaml --endpoint-url ${{ env.YC_S3_ENDPOINT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          
      - name: Get Kubeconfig and Deploy
        run: |
          # 1. Генерируем конфиг (он ложится в ~/.kube/config)
          yc managed-kubernetes cluster get-credentials ${{ secrets.KUBER_ID }} --external
          
          # 2. kubectl сам подхватит его из ~/.kube/config
          kubectl cluster-info  # Проверка связи
          
          # 3. Деплоим
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f restapi/k8s/hpa.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ env.YC_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.YC_S3_SECRET_ACCESS_KEY }}
          